#shahin.service.base.url=http://94.184.141.168:38453
#shahin.token.base.url=http://94.184.141.168:38453
#shahin.basic.auth.username=FYcXMiA1Pw
#shahin.basic.auth.password=65guEAjt2m
#cacerts.file.pass=changeit
#shahin.ignore.ssl=true

# seems it does not have any usage and should be deleted BUT ENSURE BEFORE RELEASE