spring.application.name=shahin-wrapper

server.port=8585
shahin.service.base.url=https://94.184.141.168:38453
shahin.token.base.url=https://94.184.141.168:28453
shahin.three.party.direct.url=https://ip:port/v0.3/obh/login/v0.3/obh/authorizationcode-code
shahin.datasource.url=jdbc:oracle:thin:@192.168.2.99:1521:MAINDB
shahin.datasource.username=inopay
shahin.datasource.password=inopay

shahin.datasource.driver=oracle.jdbc.driver.OracleDriver
#shahin.datasource.cachePrepStmts=true
shahin.datasource.maximumPoolSize=100
shahin.datasource.prepStmtCacheSize=100
shahin.datasource.prepStmtCacheSqlLimit=100

shahin.hibernate.dialect=org.hibernate.dialect.OracleDialect
shahin.hibernate.showSql=true
shahin.hibernate.hbm2ddl=update


# ----------------------------------------[username & password]---------------------------------------------------------
shahin.basic.auth.two.party.username=DJipctGKvG
shahin.basic.auth.two.party.password=faQ4sZWEA2
shahin.ignore.ssl=true

shahin.client.id=your-client-id
shahin.client.secret=your-client-secret
shahin.show.curl=y