spring.application.name=shahin-wrapper

server.port=8585
shahin.service.base.url=
shahin.token.base.url=
shahin.three.party.direct.url=
shahin.datasource.url=
shahin.datasource.username=
shahin.datasource.password=

shahin.datasource.driver=oracle.jdbc.driver.OracleDriver
#shahin.datasource.cachePrepStmts=true
shahin.datasource.maximumPoolSize=100
shahin.datasource.prepStmtCacheSize=100
shahin.datasource.prepStmtCacheSqlLimit=100

shahin.hibernate.dialect=org.hibernate.dialect.OracleDialect
shahin.hibernate.showSql=true
shahin.hibernate.hbm2ddl=update


# ----------------------------------------[username & password]---------------------------------------------------------
shahin.basic.auth.two.party.username=DJipctGKvG
shahin.basic.auth.two.party.password=faQ4sZWEA2
shahin.ignore.ssl=true

shahin.client.id=your-client-id
shahin.client.secret=your-client-secret
shahin.show.curl=n