spring.application.name=shahin-wrapper

spring.profiles.active=dev

#spring.security.enabled=false
#management.security.enabled=false
spring.mvc.pathmatch.matching-strategy=ant_path_matcher
#certificate.file.name=SHAHIN-SANDBOX.crt


# ----------------------------------------[generate token api]----------------------------------------------------------
shahin.get.token.path=/v0.3/obh/oauth/token

# ----------------------------------------[account api]-----------------------------------------------------------------
shahin.get.account.info.path=/v0.3/obh/api/aisp/get-account-info
shahin.get.account.balance.path=/v0.3/obh/api/aisp/get-account-balance
shahin.get.account.list.path=/v0.3/obh/api/aisp/get-account-list
shahin.get.account.statement.path=/v0.3/obh/api/aisp/get-account-statement
shahin.get.account.statement.page.path=/v0.3/obh/api/aisp/get-account-statement-with-page
shahin.service.path.two-party.get-iban=/v0.3/obh/api/aisp/get-iban
shahin.service.path.two-party.get-iban-info=/v0.3/obh/api/aisp/get-iban-info


# ----------------------------------------[iban api]--------------------------------------------------------------------
shahin.get.iban.numbre.path=/v0.3/obh/api/aisp/get-iban
shahin.get.iban.info.path=/v0.3/obh/api/aisp/get-iban-info
shahin.validate.iban.by.national.code.path=/v0.3/obh/api/inquiry/check-iban-nationalcode

# ----------------------------------------[bill api]--------------------------------------------------------------------
shahin.bill.payment.validation.path=/v0.3/obh/api/pisp/bill-payment-validation
shahin.pay.bill.path=/v0.3/obh/api/pisp/pay-bill
shahin.pay.bill.card.path = /v0.3/obh/api/card/pay-bill

# ----------------------------------------[suspend api]-----------------------------------------------------------------
shahin.block.an.account.path=/v0.3/obh/api/pisp/block-amount
shahin.account.suspension.inquiry.path=/v0.3/obh/api/pisp/block-amount-inquiry
shahin.remove.suspension.and.make.transaction.path=/v0.3/obh/api/pisp/unblock-and-transfer

# ----------------------------------------[card api]--------------------------------------------------------------------
shahin.card.balance.path = /v0.3/obh/api/card/card-balance
shahin.card.transfer.path = /v0.3/obh/api/card/card-transfer
shahin.get.card.info.path = /v0.3/obh/api/card/get-card-info
shahin.get.card.trans.path = /v0.3/obh/api/card/card-statement

# ----------------------------------------[cheque api]------------------------------------------------------------------
shahin.cheque.accept.path = /v0.3/obh/api/aisp/cheque-accept
shahin.cheque.inquiry.holder.path = /v0.3/obh/api/aisp/cheque-inquiry-holder
shahin.cheque.inquiry.transfer.path = /v0.3/obh/api/aisp/cheque-inquiry-transfer
shahin.cheque.register.path = /v0.3/obh/api/aisp/cheque-register
shahin.cheque.transfer.path = /v0.3/obh/api/aisp/cheque-transfer
shahin.get.chequebook.list.path = /v0.3/obh/api/aisp/get-chequebook-list
shahin.get.chequebook.statement.path=/v0.3/obh/api/aisp/get-cheque-statement

# ----------------------------------------[customer api]----------------------------------------------------------------
shahin.get.basic.customer.info.path=/v0.3/obh/api/aisp/get-basic-custinfo
shahin.get.detail.customer.info.path=/v0.3/obh/api/aisp/get-detail-custinfo

# ----------------------------------------[inquiry api]-----------------------------------------------------------------
shahin.ach.transactions.inquiry.path=/v0.3/obh/api/inquiry/ach-transactions-inquiry
shahin.rtgs.transactions.inquiry.path = /v0.3/obh/api/inquiry/rtgs-transactions-inquiry
shahin.check.card.nationalCode.path=/v0.3/obh/api/inquiry/check-card-nationalcode
shahin.check.medical.deserve.path=/v0.3/obh/api/inquiry/check-medical-deserve
shahin.check.phone.validity.path=/v0.3/obh/api/inquiry/check-phone-validity
shahin.customer.has.account.path=/v0.3/obh/api/inquiry/customer-has-account
shahin.customer.has.iban.path=/v0.3/obh/api/inquiry/customer-has-iban
shahin.cheque.inquiry.path=/v0.3/obh/api/inquiry/cheque-inquiry
shahin.get.insurance.history.path=/v0.3/obh/api/inquiry/get-insurance-history
shahin.get.national.identity.path=/v0.3/obh/api/inquiry/get-national-identity
shahin.transaction.confirmation.path=/v0.3/obh/api/pisp/transfer-validation
shahin.transactions.inquiry.path=/v0.3/obh/api/pisp/transaction-inquiry

# ----------------------------------------[loan api]--------------------------------------------------------------------
shahin.get.loan.info.path=/v0.3/obh/api/aisp/get-loan-info
shahin.get.loan.statement.path=/v0.3/obh/api/aisp/get-loan-statement

# ----------------------------------------[(rtgs-ach-api)]--------------------------------------------------------------
shahin.local.transaction.path=/v0.3/obh/api/pisp/transfer-to
shahin.transaction.path=/v0.3/obh/api/pisp/transfer

# ----------------------------------------[personal-validation-api]-----------------------------------------------------
shahin.national.code.and.iban.number.validation.path=/v0.3/obh/api/inquiry/check-iban-nationalcode
shahin.validate.mobile.number.path=/v0.3/obh/api/inquiry/check-phone-validity
shahin.validate.card.by.national.code.path=/v0.3/obh/api/inquiry/check-card-nationalcode

# ----------------------------------------Logging levels----------------------------------------------------------------
logging.level.org.springframework.web.reactive=DEBUG
logging.level.reactor.netty=DEBUG
logging.level.org.springframework.web=ERROR
logging.level.org.springframework.web.servlet.mvc.method.annotation=TRACE
logging.level.biz.espc.shahin=DEBUG
logging.level.root=ERROR
spring.main.log-startup-info=true
logging.level.biz.espc.common=DEBUG
logging.level.biz.espc.two-party-protocol=DEBUG
logging.level.biz.espc.three-party-protocol=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

# Logging to file
logging.file.path=logs
#logging.file.name=shahin-wrapper.log
logging.file.name=${spring.application.name}.log
# Logging patterns
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - [%X{traceId}] %msg%n
#*****************************************[THREE PARTY API PATH]********************************************************


# ----------------------------------------[three-party properties]------------------------------------------------------
shahin.three.party.auth.url=https://ip:port/v0.3/obh/login
shahin.three.party.auth.redirect.uri=/v0.3/obh/authorizationcode-code
shahin.three.party.auth.client.id=FYcXMiA1Pw
shahin.three.party.base.url=https://10.10.10.112:38453/v0.2/obh/api/aisp/get-account-list